server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}
